### ISSUE TITLE
Error building ios in xcode 9.2

### ISSUE THREAD

**Issue by CesarBalzer** [dpa99c/cordova-plugin-firebasex-test#1]
I made the clone as it describes by adding the platforms and running, but on ios I get some errors.
What am I forgetting or doing wrong for kindness?

Build target FirebaseTest of project FirebaseTest with configuration Debug

Ld /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/FirebaseTest.app/FirebaseTest normal x86_64
    cd /Users/balzer/www/cordova-plugin-firebase-test/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -L/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/FirebaseAuth -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/FirebaseCore -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/FirebaseInstanceID -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/FirebaseMessaging -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/GoogleUtilities -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/Protobuf -F/Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/nanopb -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/Crashlytics/iOS -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/Fabric/iOS -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/FirebaseABTesting/Frameworks -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/FirebasePerformance/Frameworks -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/FirebaseRemoteConfig/Frameworks -F/Users/balzer/www/cordova-plugin-firebase-test/platforms/ios/Pods/GoogleAppMeasurement/Frameworks -filelist /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/FirebaseTest.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/FirebaseTest_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -ObjC -lc++ -lsqlite3 -lz -framework CoreTelephony -framework Crashlytics -framework FIRAnalyticsConnector -framework Fabric -framework FirebaseABTesting -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebasePerformance -framework FirebaseRemoteConfig -framework Foundation -framework GTMSessionFetcher -framework GoogleAppMeasurement -framework GoogleToolboxForMac -framework GoogleUtilities -framework Protobuf -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework nanopb -weak_framework UserNotifications -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/FirebaseTest.app.xcent /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/libCordova.a -framework Pods_FirebaseTest -Xlinker -dependency_info -Xlinker /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/FirebaseTest_dependency_info.dat -o /Users/balzer/Library/Developer/Xcode/DerivedData/FirebaseTest-fhowossayshwxpdgqpcmfbvmzwhr/Build/Products/Debug-iphonesimulator/FirebaseTest.app/FirebaseTest

Undefined symbols for architecture x86_64:
  "_sqlite3_prepare_v3", referenced from:
      -[APMSqliteStore prepareSQL:error:] in GoogleAppMeasurement(APMSqliteStore_645df61703f07a6639f4b1de4d0cf5c3.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

**Comment by dpa99c** [comment]
Please try the following:

- Ensure Cocoapods is installed and updated [see here](https://github.com/dpa99c/cordova-plugin-firebase#cocoapods)
- If building your project in Xcode, you need to open `FirebaseTest.xcworkspace` (not FirebaseTest.xcodeproj) so both your Cordova app project and the Pods project will be loaded into Xcode.
- Update to Xcode 10

**Comment by CesarBalzer** [comment]
So I can not compile, I can not update xcode to version 10, I'm using outdated mac and xcode, I have video problems of this version of macbook pro, I still can not resolve it in Brazil, so I did not upgrade to Mojave or High Sierra. Unfortunately if I have no other way I will have to abandon the ios developer career with my equipment.
The old version of firebase that you made available the link (https://github.com/dpa99c/cordova-plugin-firebase.git#GH-1057-April-05-android-build-issue) a few months ago works almost completely so far.
So tell me if I can still be using this patch version for now, or how much I can use on this device, until maybe one day I can solve this problem or buy other equipment.
If you know of any further problems I may have with this version of O.S and Hardware I will be grateful if you can inform me.
This is the version of MBP:
![Captura de Tela 2019-07-01 às 10 43 53](https://user-images.githubusercontent.com/13343041/60442035-8f49a200-9bee-11e9-8fe6-5fe6ed05b6e6.png)

Thanks for all the help Dave

**Comment by dpa99c** [comment]
Did you try the first two things with Xcode 9?

> - Ensure Cocoapods is installed and updated [see here](https://github.com/dpa99c/cordova-plugin-firebase#cocoapods)
> - If building your project in Xcode, you need to open `FirebaseTest.xcworkspace` (not FirebaseTest.xcodeproj) so both your Cordova app project and the Pods project will be loaded into Xcode.

If so, there's a couple of other things to try:
- re-run the test with the latest version of this plugin which fixes some iOS build issues (e.g. [this one](https://stackoverflow.com/a/26903572/777265) by adding `$(inherited)`)
    - make sure you completely wipe down the existing test project: `rm -Rf cordova-plugin-firebase-test`
- Have a look at [this SO post](https://stackoverflow.com/a/42922707/777265)
