### ISSUE TITLE
Failed to fetch platform cordova-ios@^5.0.0  

### ISSUE THREAD

**Issue by shinjiro-itagaki** [dpa99c/cordova-plugin-firebasex-test#11]
following is output 

=========
cordova-plugin-firebasex-test $ cordova platform add ios
Using cordova-fetch for cordova-ios@^5.0.0
(node:49610) Warning: Accessing non-existent property 'ios' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Failed to fetch platform cordova-ios@^5.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Could not determine package name from output:
audited 173 packages in 2.203s

7 packages are looking for funding
  run `npm fund` for details
 
found 1 high severity vulnerability 
  run `npm audit fix` to fix them, or `npm audit` for details  

==========

and this issue has reported
https://github.com/apache/cordova-ios/issues/516

**Comment by dpa99c** [comment]
Not sure how it's failing on `cordova-ios@^5.0.0` since the [pinned version](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/package.json#L42) is `^6.1.1`.

This works fine in my development env:

    git clone https://github.com/dpa99c/cordova-plugin-firebasex-test
    cd cordova-plugin-firebasex-test
    cordova platform add ios
    cordova build ios --emulator

**Comment by free-bots** [comment]
@shinjiro-itagaki got the same issue and solved it with upgrading cordova `npm install -g cordova`

**Comment by burtsevyg** [comment]
add     
"cordova-ios": "6.1.1", 
to "dependencies" fix problem.

**Comment by burtsevyg** [comment]
But now I get other problem:
```
platforms/ios/Runner/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found
@import FirebaseFirestore;
 ~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by burtsevyg** [comment]
New version cordova fix problem.
