### ISSUE TITLE
Now FirebaseInstanceId.getInstance().getToken() is  deprecated.

### ISSUE THREAD

**Issue by Crazyang** [dpa99c/cordova-plugin-firebasex-test#15]
Envirement 
  "cordova-android": "^9.0.0",
    "cordova-browser": "~6.0.0",
    "cordova-custom-config": "^5.1.0",
    "cordova-ios": "^6.2.0",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-console": "^1.1.0",
    "cordova-plugin-enable-multidex": "^0.2.0",
    "cordova-plugin-firebasex": "^11.0.3",
    "cordova-plugin-whitelist": "~1.3.4",
    "cordova-plugin-wkwebview-file-xhr": "^3.0.0"

Now  i used android to get token  is null ,  i check the plugin code , find an function getToken() is  deprecated.
So i check it on firebase on https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId. 

And it suggestion we maybe need to change it into  FirebaseInstallations to get token 

Or there are another reason for causing  app can not get token.

**Comment by dpa99c** [comment]
The plugin now uses Firebase Installations SDK
