### ISSUE TITLE
Error 10, Unknown server client ID when authenticate with Google

### ISSUE THREAD

**Issue by dektiram** [dpa99c/cordova-plugin-firebasex-test#16]
Cordova android.
Several months ago I try this repo is running well, but some days ago I fresh clone and try again get some error.

Fresh clone from this repository.
Configuring SERVER_CLIENT_ID with OAuth Client ID which auto generated from firebase create android app.
I also already copy google-service.json to my project
I double check that my SHA1 is correct, but I still get error "Unknown server client ID".
Is any change from google terms or any config I missing ?

**Comment by jesusduranevenbytes** [comment]
The same happening here, it does not work with my client ID. I tried using both Web Application's Client ID and Android's Client ID and neither of them work.

Is there any extra configuration needed?

**Comment by moshi100** [comment]
Hi, I am facing the same issue. is someone solve it?

**Comment by MiguiTE** [comment]
I am also facing this  "Unknown server client ID" issue. Any help?

**Comment by moshi100** [comment]
I fixed it by adding to firebase console SHA-1 android debug, on windows run the command below:
`keytool -list -v -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore`

Check this link for more details: https://developers.google.com/android/guides/client-auth?authuser=0

**Comment by jesusduranevenbytes** [comment]
Yes! That works!
