### ISSUE TITLE
What is controlling the icon color on Android?

### ISSUE THREAD

**Issue by conrad10781** [dpa99c/cordova-plugin-firebasex-test#2]
I'm noticing that bell.png appears to be getting applied a custom color ( #008487 ) from what I can get from my screenshot.

![Screenshot_20190926-131312](https://user-images.githubusercontent.com/238705/65710376-e5e54180-e060-11e9-9f68-0948cb743d39.png)

How can I remove this? I wanted to use a different icon all together, but it appears this color is being applied over it:

![Screenshot_20190926-132729](https://user-images.githubusercontent.com/238705/65710823-bbe04f00-e061-11e9-95d7-e227cd6c4428.png)

**Comment by dpa99c** [comment]
You can define a default notification accent colour for Android as [documented here](https://github.com/dpa99c/cordova-plugin-firebasex#android-notification-color)
