### ISSUE TITLE
Build error on Xcode 13.4.1 with IPHONEOS_DEPLOYMENT_TARGET (possible fix)

### ISSUE THREAD

**Issue by laurentperez** [dpa99c/cordova-plugin-firebasex-test#25]
hello

I'm migrating a project using your plugin and I'm always checking first that your example project is building as you mentionned in several tickets to do so

however `cordova run ios` fails with

```
/Users/itk/Desktop/cordova-plugin-firebasex-test/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'leveldb-library' from project 'Pods')
/Users/itk/Desktop/cordova-plugin-firebasex-test/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'AppAuth' from project 'Pods')
** BUILD FAILED **
```

this is because since Xcode 12 (I think) it does not allow to target iOS 8 anymore.

we had the same problem and did the following very dirty fix

`sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 8/IPHONEOS_DEPLOYMENT_TARGET = 9/g' platforms/ios/Pods/Pods.xcodeproj/project.pbxproj`

the sed is ugly, when future Xcode will drop iOS9 it will break again

it all boils down to "old" Pods but I don't know how to fix it.

do you have a better fix ?

**Comment by dpa99c** [comment]
Minimum deployment target is [now set to iOS v11](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/config.xml#L69) for this project. Also advise testing on a real iOS device not the iOS Simulator.
