### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by kostyanet** [dpa99c/cordova-plugin-firebasex-test#26]
I'm experiencing the following issue building the project. Please help!
<img width="864" alt="image" src="https://user-images.githubusercontent.com/21313651/191441337-0addc4f9-7a85-426c-a337-ea7475b3892d.png">

**Comment by dpa99c** [comment]
Run on a real iOS device, not the iOS Simulator
