### ISSUE TITLE
I do not receive notifications on iOS

### ISSUE THREAD

**Issue by Chashy-k** [dpa99c/cordova-plugin-firebasex-test#32]
I build cordova app for android and ios, with Firebase.
On android it works perfect.
On IOS messages are not received on the phone.
Everything seems right -
I receive FCM and APNS tokens.
permission popup is shown for FirebasePlugin.grantPermission

I tried to follow this sample, step by step, but got this error -
cordova.plugin.customfcmreceiver.registerReceiver is not a function
What is the purpose of this plugin?

What else could be the problem if receiving the token?

**Comment by dpa99c** [comment]
`cordova-plugin-customfcmreceiver` is an example plugin that is [bundled with this project](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/plugins/cordova-plugin-customfcmreceiver) to illustrate how a custom message receiver can be implemented to handle specific types of message in place of the default handling.
Maybe the plugin has not installed correctly in your environment - you can check is is in `plugins/` and if so try removing and re-adding the iOS platform: `cordova platform rm ios && cordova platform add ios`.

Be sure to use the [built-in messaging client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) to test cloud messaging functionality.

This plugin is used in multiple production apps and FCM notifications are working correctly so closing this.
If evidence is provided to the contrary, this can be re-opened.
