### ISSUE TITLE
Default Notification Accent Color in Android

### ISSUE THREAD

**Issue by conrad10781** [dpa99c/cordova-plugin-firebasex-test#4]
@dpa99c , I tried to report this in my original ticket ( #2 ), but you closed it before I got a chance.

When using 00FFFFFF either in a message, or as the value of the plugin variable ANDROID_ICON_ACCENT , I'm expecting transparency so I can see my supplied logo as expected. Is that not the case?

**Comment by dpa99c** [comment]
#00FFFFFF in ARGB space would represent an alpha of 0, hence I'd expect the notification icon not to be visible at all.

**Comment by conrad10781** [comment]
I would have thought that FFFFFFFF would have made it so that I can't see it at all? Well, it would have eliminated the transparency. What can I use so that I can see my supplied icon that already has it's color in it, essentially eliminating the accent?

**Comment by dpa99c** [comment]
> I would have thought that FFFFFFFF would have made it so that I can't see it at all?

00 = 0 (transparent), FF = 1(opaque)

> What can I use so that I can see my supplied icon that already has it's color in it, essentially eliminating the accent?

The default (small) notification icon on Android only supports monochrome - the colour of your original icon is irrelevant as Android will only render it with in a single colour - that which is specified by the colour accent.

The plugin supports [large notification icons for Android](https://github.com/dpa99c/cordova-plugin-firebasex#android-large-notification-icon) which can be polychromatic but Firebase doesn't currently support these itself so they can only be displayed in data or foreground notifications. See [the Android notifications documentation](https://developer.android.com/guide/topics/ui/notifiers/notifications) for details.
