### ISSUE TITLE
Issue While setting-up Test project

### ISSUE THREAD

**Issue by guptsachin** [dpa99c/cordova-plugin-firebasex-test#6]
Hi Dave,

I'm trying to run the test project as you documented but getting following error.

Gradle sync failed: In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[20.0.
				0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
				Dependency failing: com.google.firebase:firebase-messaging:20.0.0 -> com.google.firebase:firebase-iid@[20.0.0], but fire
				base-iid version was 20.0.2.
				The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
				ifact with the issue.
				-- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-api@{strictly 17.0.0}
				-- Project 'app' depends onto com.google.firebase:firebase-messaging@20.0.0
				-- Project 'app' depends onto com.google.firebase:firebase-analytics@17.2.1
				-- Project 'app' depends onto com.google.firebase:firebase-config@{strictly 19.0.3}
				-- Project 'app' depends onto com.google.firebase:firebase-perf@19.0.1
				-- Project 'app' depends onto com.google.android.gms:play-s... (show balloon)
![Screenshot 2020-02-27 at 11 09 06 PM](https://user-images.githubusercontent.com/22422589/75470309-7e884080-59b6-11ea-8552-297ad7ab53dc.png)

I'm not sure about this error. In fact same error we were getting while using the firebase plugin.
 Please look into this. Your help is appreciated.

Thanks.
SG

**Comment by dpa99c** [comment]
The example project works fine in my build environment - see this [console output](https://pastebin.com/brQQMnvx) - please run these same commands in your environment and confirm if the build is successful:

    git clone https://github.com/dpa99c/cordova-plugin-firebasex-test/ &&  cd cordova-plugin-firebasex-test/

    # you will have to replace this with your own google-services.json and change the id in config.xml if necessary
    cp /some/path/to/google-services.json . 

    cordova platform add android

    cordova build android

**Comment by guptsachin** [comment]
Hi Dave,

Thanks for sharing detail output. This was the problem with my environment ( ANDROID_SDK_HOME was missing) and I was adding firebase SDK in project and app Gradle as per instructions by firebase.

I added SDK home and removed firebase SDK entries from project and app Gradle files and now it's working perfectly.
 
Thanks.
SG
