### ISSUE TITLE
Get APNS returning null value

### ISSUE THREAD

**Issue by sboudouk** [dpa99c/cordova-plugin-firebasex-test#9]
Using iOS build, Get APNS returns a null value. Also, I do not receive notifications on iOS, so, are this related to APNS ?

The project is correctly set on Firebase & App Center. Is this normal or does it requires a step that i'm not aware of ? 

Also do I really need APNS Token to send notfication to specific users ? Can't I also use FCM Token ?

**Comment by mrigsby** [comment]
I was having a similar issue until I realized I wasn't calling FirebasePlugin.grantPermission when the app first opened. Before doing this the FirebasePlugin.getAPNSToken was returning null. And yes, once FirebasePlugin has an APNS token you can still use the FCM token to send notifications which by default will be a APNS notification if the app is closed or in the background.

https://github.com/dpa99c/cordova-plugin-firebasex#grantpermission

**Comment by sboudouk** [comment]
```
[Log] deviceready (cordova.js, line 1540)
[Log] Auto init is enabled (cordova.js, line 1540)
[Log] User is not signed in (cordova.js, line 1540)
[Log] APNS token received: b48448e02dedc220dd36106272c3fc09ab75b9167f04a78aa9f37e7868ed287b (cordova.js, line 1540)
[Log] Analytics data collection setting is disabled (cordova.js, line 1540)
[Log] Performance data collection setting is disabled (cordova.js, line 1540)
[Log] Crashlytics data collection setting is disabled (cordova.js, line 1540)
[Log] Crashlytics data collection is currently disabled for this session (cordova.js, line 1540)
[Log] Token refreshed: eaA1IS8mPURnnJtrRsekHW:APA91bE7dUTjMaoCMfTvEL8dHJO9eeoGwiyV68oLgH_xSTn9Gl3YRQgiRl2LnaSpXvhwLfDzREkUyho7ympEOnix1sh5TSaCDrKxE3yo_l5x-i0RLkM75ynj92STx04g-LYnYYof1bKk (cordova.js, line 1540)
[Log] Remote notifications permission granted (cordova.js, line 1540)
[Log] Got FCM token: eaA1IS8mPURnnJtrRsekHW:APA91bE7dUTjMaoCMfTvEL8dHJO9eeoGwiyV68oLgH_xSTn9Gl3YRQgiRl2LnaSpXvhwLfDzREkUyho7ympEOnix1sh5TSaCDrKxE3yo_l5x-i0RLkM75ynj92STx04g-LYnYYof1bKk (cordova.js, line 1540)
[Log] Got APNS token: b48448e02dedc220dd36106272c3fc09ab75b9167f04a78aa9f37e7868ed287b (cordova.js, line 1540)
```

Exactly, it solved my issue. Thanks.

**Comment by mrigsby** [comment]
No Problem. Glad it helped.
